// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQoXmHPD0qO90eBlMwrU5Exx-epjJ0BeE',
    appId: '1:578929683605:web:613e6bffcc9af6c2447f9c',
    messagingSenderId: '578929683605',
    projectId: 'flutter-firebase-1161d',
    authDomain: 'flutter-firebase-1161d.firebaseapp.com',
    storageBucket: 'flutter-firebase-1161d.firebasestorage.app',
    measurementId: 'G-3C522JTZHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0v9CGd93_aDh_kTKV1qbNwacmj4p82v4',
    appId: '1:578929683605:android:76274f56ae38b5b9447f9c',
    messagingSenderId: '578929683605',
    projectId: 'flutter-firebase-1161d',
    storageBucket: 'flutter-firebase-1161d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxO-DSSbtxsqHQmdcW8njkHDs6Dfy4Ttw',
    appId: '1:578929683605:ios:6bd656efe183718a447f9c',
    messagingSenderId: '578929683605',
    projectId: 'flutter-firebase-1161d',
    storageBucket: 'flutter-firebase-1161d.firebasestorage.app',
    iosBundleId: 'com.example.fHak',
  );

}